#!/usr/bin/env zsh
#
# run_tests.zsh - Automated test runner for the sorter.
#
# For every fixture case under tests/fixtures/<case>/ (as generated by
# generate_fixtures.zsh) it:
#   1. runs the sorter in an isolated sandbox directory,
#   2. checks the exit code,
#   3. checks the generated output file name (extension handling,
#      hidden files, etc.),
#   4. compares the generated output content with the expected file,
#   5. verifies whether a WARN log was (not) expected.
#
# Usage:  ./run_tests.zsh [-k]
#   -k  keep the sandbox directories for inspection
#
set -uo pipefail

SCRIPT_DIR="${0:A:h}"
ROOT="${SCRIPT_DIR:h}"
BINARY="${ROOT}/sorter"
FIX="${SCRIPT_DIR}/fixtures"
SANDBOX_ROOT="${SCRIPT_DIR}/_sandbox"

KEEP=0
[[ ${1:-} == "-k" ]] && KEEP=1

# ---- preconditions ---------------------------------------------------
if [[ ! -x $BINARY ]]; then
  print "Building sorter ..."
  ( cd "$ROOT" && cc -Wall -Wextra -O2 -o sorter \
      main.c logging.c list.c io.c mergesort.c -pthread ) || {
    print -u2 "Build failed."; exit 1 }
fi
if [[ ! -d $FIX ]]; then
  print "No fixtures found; generating ..."
  zsh "${SCRIPT_DIR}/generate_fixtures.zsh"
fi

rm -rf "$SANDBOX_ROOT"
mkdir -p "$SANDBOX_ROOT"

pass=0; fail=0
ok()   { pass=$((pass + 1)); print "      ✓ $1"; }
bad()  { fail=$((fail + 1)); print "      ✗ $1"; }

# ---- run every case ---------------------------------------------------
for meta in "$FIX"/*/.meta (N); do
  dir="${meta:h}"
  case_name="${dir:t}"

  # read .meta
  order=asc; input=; output=; exit_code=0; expect_warn=no; use_default=no
  while IFS='=' read -r k v; do
    case $k in
      order) order=$v ;;
      input) input=$v ;;
      output) output=$v ;;
      exit) exit_code=$v ;;
      expect_warn) expect_warn=$v ;;
      use_default) use_default=$v ;;
    esac
  done < "$meta"

  # sandbox for this case (isolated dir; run from inside it so the
  # output file lands next to the input copy)
  sb="$SANDBOX_ROOT/$case_name"
  mkdir -p "$sb"
  cp "$dir/$input" "$sb/"

  log="$sb/run.log"
  (
    cd "$sb"
    if [[ $use_default == yes ]]; then
      "$BINARY" "$input"
    else
      "$BINARY" --order "$order" "$input"
    fi
  ) > /dev/null 2> "$log"
  actual_exit=$?

  print "== $case_name =="

  # 1. exit code
  if (( actual_exit == exit_code )); then
    ok "exit code is $exit_code"
  else
    bad "exit code expected $exit_code, got $actual_exit"
  fi

  # 2. generated output file name
  #    Files in the sandbox other than the input, run.log, exit file.
  generated=()
  # scan both regular and hidden (dot) files; each glob pattern carries
  # its own nullglob qualifier so no-match never errors.
  # Filter by full path: for hidden inputs (e.g. .secret) the input
  # itself would also match the .* glob and must be excluded.
  for f in "$sb"/*(ND) "$sb"/.*(ND); do
    base="${f:t}"
    [[ $base == . || $base == .. ]] && continue
    [[ $f == "$sb/$input" || $f == "$sb/run.log" ]] && continue
    generated+=("$base")
  done

  if [[ $output != NONE ]]; then
    cnt=${#generated[@]}
    first=${generated[1]}
    if (( cnt == 1 )) && [[ "$first" == "$output" ]]; then
      ok "output file named \"$output\""
    else
      bad "output file expected \"$output\", found: ${generated[@]}"
    fi

    # 3. content comparison
    if [[ -f "$sb/$output" ]]; then
      if diff -q "$dir/$output" "$sb/$output" > /dev/null 2>&1; then
        ok "content matches expected ($output)"
      else
        bad "content mismatch for $output:"
        diff "$dir/$output" "$sb/$output" | head -10 | sed 's/^/          /'
      fi
    else
      bad "expected output file \"$output\" was not created"
    fi
  else
    # no output must exist at all
    if (( ${#generated[@]} == 0 )); then
      ok "no output file written (as expected)"
    else
      bad "unexpected output file(s): ${generated[@]}"
    fi
  fi

  # 4. WARN log expectation
  if grep -q "\[WARN " "$log" 2> /dev/null; then got_warn=yes; else got_warn=no; fi
  if [[ $expect_warn == $got_warn ]]; then
    ok "WARN as expected ($got_warn)"
  else
    bad "WARN expected=$expect_warn got=$got_warn"
  fi
done

# ---- summary ----------------------------------------------------------
print ""
print "==================================================="
print " Results: $pass passed, $fail failed"
print "==================================================="

if (( KEEP )); then
  print "Sandbox kept at: $SANDBOX_ROOT"
else
  rm -rf "$SANDBOX_ROOT"
fi

(( fail == 0 )) || exit 1
exit 0
