#!/usr/bin/env zsh
#
# run_tests.zsh - Automated test runner for the sorter.
#
# For every fixture case under tests/fixtures/<case>/ (as generated by
# generate_fixtures.zsh) it:
#   1. runs the sorter in an isolated sandbox directory,
#   2. checks the exit code,
#   3. checks the generated output file name (extension handling,
#      hidden files, etc.),
#   4. compares the generated output content with the expected file,
#   5. verifies whether a WARN log was (not) expected.
#
# Usage:  ./run_tests.zsh [-k]
#   -k  keep the sandbox directories for inspection
#
set -uo pipefail

SCRIPT_DIR="${0:A:h}"
ROOT="${SCRIPT_DIR:h}"
BINARY="${ROOT}/sorter"
FIX="${SCRIPT_DIR}/fixtures"
SANDBOX_ROOT="${SCRIPT_DIR}/_sandbox"

KEEP=0
[[ ${1:-} == "-k" ]] && KEEP=1

# M-08 fix: deterministic environment for all test invocations.
export LC_ALL=C

# ---- preconditions ---------------------------------------------------
if [[ ! -x $BINARY ]]; then
  print "Building sorter ..."
  ( cd "$ROOT" && make build ) || {
    print -u2 "Build failed."; exit 1 }
fi
if [[ ! -d $FIX ]]; then
  print "No fixtures found; generating ..."
  zsh "${SCRIPT_DIR}/generate_fixtures.zsh"
fi

rm -rf "$SANDBOX_ROOT"
mkdir -p "$SANDBOX_ROOT"

pass=0; fail=0; cases=0
ok()   { pass=$((pass + 1)); print "      ✓ $1"; }
bad()  { fail=$((fail + 1)); print "      ✗ $1"; }

# ---- run every case ---------------------------------------------------
# M-09 fix: single glob with (ND) already includes dotfiles.
for meta in "$FIX"/*/.meta(N); do
  dir="${meta:h}"
  case_name="${dir:t}"
  cases=$((cases + 1))

  # read .meta
  order=asc; input=; output=; exit_code=0; expect_warn=no; use_default=no; use_dashdash=no
  while IFS='=' read -r k v; do
    case $k in
      order) order=$v ;;
      input) input=$v ;;
      output) output=$v ;;
      exit) exit_code=$v ;;
      expect_warn) expect_warn=$v ;;
      use_default) use_default=$v ;;
      use_dashdash) use_dashdash=$v ;;
    esac
  done < "$meta"

  # sandbox for this case
  sb="$SANDBOX_ROOT/$case_name"
  mkdir -p "$sb"
  cp "$dir/$input" "$sb/"

  log="$sb/run.log"
  # M-08 fix: force LOG_LEVEL=INFO for consistent test behavior.
  (
    cd "$sb"
    if [[ $use_default == yes ]]; then
      LOG_LEVEL=INFO "$BINARY" "$input"
    elif [[ $use_dashdash == yes ]]; then
      LOG_LEVEL=INFO "$BINARY" --order "$order" -- "$input"
    else
      LOG_LEVEL=INFO "$BINARY" --order "$order" "$input"
    fi
  ) > /dev/null 2> "$log"
  actual_exit=$?

  print "== $case_name =="

  # 1. exit code
  if (( actual_exit == exit_code )); then
    ok "exit code is $exit_code"
  else
    bad "exit code expected $exit_code, got $actual_exit"
  fi

  # 2. generated output file name
  #    M-09 fix: single glob covering both normal and hidden files.
  generated=()
  for f in "$sb"/*(ND.); do
    base="${f:t}"
    [[ $f == "$sb/$input" || $f == "$sb/run.log" ]] && continue
    generated+=("$base")
  done

  if [[ $output != NONE ]]; then
    cnt=${#generated[@]}
    first=${generated[1]:-}
    if (( cnt == 1 )) && [[ "$first" == "$output" ]]; then
      ok "output file named \"$output\""
    else
      bad "output file expected \"$output\", found: ${generated[*]:-<none>}"
    fi

    # 3. content comparison
    if [[ -f "$sb/$output" ]]; then
      if diff -q "$dir/$output" "$sb/$output" > /dev/null 2>&1; then
        ok "content matches expected ($output)"
      else
        bad "content mismatch for $output:"
        diff "$dir/$output" "$sb/$output" | head -10 | sed 's/^/          /'
      fi
    else
      bad "expected output file \"$output\" was not created"
    fi
  else
    # no output must exist at all
    if (( ${#generated[@]} == 0 )); then
      ok "no output file written (as expected)"
    else
      bad "unexpected output file(s): ${generated[*]}"
    fi
  fi

  # 4. WARN log expectation
  if grep -q "\[WARN " "$log" 2> /dev/null; then got_warn=yes; else got_warn=no; fi
  if [[ $expect_warn == $got_warn ]]; then
    ok "WARN as expected ($got_warn)"
  else
    bad "WARN expected=$expect_warn got=$got_warn"
  fi
done

# M-07 fix: require at least one test case.
if (( cases == 0 )); then
  print -u2 "ERROR: no test cases found under $FIX"
  exit 1
fi

# ---- integration tests (scenarios beyond fixture framework) -----------
print ""
print "== Integration tests =="

# I-1: H-01 regression - dotted parent directory
print "  -- H-01: dotted parent directory --"
itg_dir="$SANDBOX_ROOT/_integration"
mkdir -p "$itg_dir/release.v1.2"
printf 'cherry\napple\nbanana\n' > "$itg_dir/release.v1.2/data"
(LOG_LEVEL=INFO "$BINARY" --order asc "$itg_dir/release.v1.2/data") > /dev/null 2>&1
if [[ -f "$itg_dir/release.v1.2/data_ordered_asc" ]]; then
  ok "H-01: output beside input in dotted-parent dir"
  expected=$(printf 'apple\nbanana\ncherry\n')
  actual=$(cat "$itg_dir/release.v1.2/data_ordered_asc")
  if [[ "$actual" == "$expected" ]]; then
    ok "H-01: content correct with dotted parent"
  else
    bad "H-01: content mismatch with dotted parent"
  fi
else
  bad "H-01: output not created beside input (dotted parent dir)"
fi

# I-2: H-02 regression - symlink at output path is replaced, not followed
print "  -- H-02: symlink at output not followed --"
mkdir -p "$itg_dir/symlink_test"
printf 'beta\nalpha\n' > "$itg_dir/symlink_test/input.txt"
mkdir -p "$itg_dir/symlink_test/trap"
ln -sf "$itg_dir/symlink_test/trap/victim" "$itg_dir/symlink_test/input_ordered_asc.txt"
(LOG_LEVEL=INFO "$BINARY" --order asc "$itg_dir/symlink_test/input.txt") > /dev/null 2>&1
if [[ -f "$itg_dir/symlink_test/input_ordered_asc.txt" ]] && \
   [[ ! -L "$itg_dir/symlink_test/input_ordered_asc.txt" ]]; then
  ok "H-02: symlink replaced with regular file"
else
  bad "H-02: symlink was followed or output missing"
fi
if [[ ! -e "$itg_dir/symlink_test/trap/victim" ]]; then
  ok "H-02: symlink target was not created"
else
  bad "H-02: symlink target was written to"
fi

# I-3: M-01 regression - output permissions match input
print "  -- M-01: permission preservation --"
mkdir -p "$itg_dir/perm_test"
printf 'beta\nalpha\n' > "$itg_dir/perm_test/secret.txt"
chmod 600 "$itg_dir/perm_test/secret.txt"
(LOG_LEVEL=INFO "$BINARY" --order asc "$itg_dir/perm_test/secret.txt") > /dev/null 2>&1
if [[ -f "$itg_dir/perm_test/secret_ordered_asc.txt" ]]; then
  out_perms=$(stat -f '%Lp' "$itg_dir/perm_test/secret_ordered_asc.txt")
  if [[ "$out_perms" == "600" ]]; then
    ok "M-01: output is 0600 matching input"
  else
    bad "M-01: output perms are $out_perms, expected 600"
  fi
else
  bad "M-01: output file not created"
fi

# I-4: M-03 regression - stale output replaced by empty run
print "  -- M-03: stale output replaced --"
mkdir -p "$itg_dir/stale_test"
printf 'stale content\n' > "$itg_dir/stale_test/empty_ordered_asc.txt"
: > "$itg_dir/stale_test/empty.txt"
(LOG_LEVEL=INFO "$BINARY" --order asc "$itg_dir/stale_test/empty.txt") > /dev/null 2>&1
if [[ -f "$itg_dir/stale_test/empty_ordered_asc.txt" ]]; then
  stale_size=$(wc -c < "$itg_dir/stale_test/empty_ordered_asc.txt" | tr -d ' ')
  if (( stale_size == 0 )); then
    ok "M-03: stale output replaced with empty file"
  else
    bad "M-03: stale output NOT replaced (size=$stale_size)"
  fi
else
  bad "M-03: output file missing after empty run"
fi

# I-5: H-01 regression - ./relative dotfile path
print "  -- H-01: ./ relative dotfile --"
mkdir -p "$itg_dir/dotfile_rel"
printf 'charlie\nalpha\n' > "$itg_dir/dotfile_rel/.secret"
(cd "$itg_dir/dotfile_rel" && LOG_LEVEL=INFO "$BINARY" --order asc ./.secret) > /dev/null 2>&1
if [[ -f "$itg_dir/dotfile_rel/.secret_ordered_asc" ]]; then
  ok "H-01: ./.secret -> .secret_ordered_asc (no false extension)"
else
  bad "H-01: dotfile with ./ prefix failed"
fi

# ---- summary ----------------------------------------------------------
print ""
print "==================================================="
print " Results: $pass passed, $fail failed ($cases cases)"
print "==================================================="

if (( KEEP )); then
  print "Sandbox kept at: $SANDBOX_ROOT"
else
  rm -rf "$SANDBOX_ROOT"
fi

(( fail == 0 )) || exit 1
exit 0
